import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const BeVietnamPro = Be_Vietnam_Pro({ subsets: ["latin"] ,
  weight: "400"
});

export const metadata = {
  title: "Country Page-World Ranks",
  description: "Generated by Andres Franco Langthon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={BeVietnamPro.className}>{children}</body>
    </html>
  );
}
